### ISSUE TITLE
passing variables

### ISSUE THREAD

**Issue by therealelyayo** [DykemaBill/redirector#1]
would it be possible to append ?email=jackson@be.com to these redirect and then using the domain of the email to redirect somewhere ,
example?email=t@gmail.com would goto gmail.com

and t@yahoo.com shuld got yahoo.com

would that be possible

**Comment by DykemaBill** [comment]
I am sure it would with just a small change in how the redirect is handled.  Have you tried forking it just to see?

**Comment by DykemaBill** [comment]
Just a question, not really an issue.
